/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as RequestGameRouteImport } from './routes/request-game'
import { Route as RandomRouteImport } from './routes/random'
import { Route as ConsoleGamesRouteImport } from './routes/console-games'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedMessagesPeerIdRouteImport } from './routes/_authenticated/messages/$peerId'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminPostsIndexRouteImport } from './routes/_authenticated/admin/posts/index'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin/posts/$id'

const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestGameRoute = RequestGameRouteImport.update({
  id: '/request-game',
  path: '/request-game',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleGamesRoute = ConsoleGamesRouteImport.update({
  id: '/console-games',
  path: '/console-games',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedMessagesPeerIdRoute =
  AuthenticatedMessagesPeerIdRouteImport.update({
    id: '/messages/$peerId',
    path: '/messages/$peerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsIndexRoute =
  AuthenticatedAdminPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/posts/$id',
    path: '/posts/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/community': typeof CommunityRouteWithChildren
  '/console-games': typeof ConsoleGamesRoute
  '/random': typeof RandomRoute
  '/request-game': typeof RequestGameRoute
  '/software': typeof SoftwareRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/community/$postId': typeof CommunityPostIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/games/': typeof GamesIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/messages/$peerId': typeof AuthenticatedMessagesPeerIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/community': typeof CommunityRouteWithChildren
  '/console-games': typeof ConsoleGamesRoute
  '/random': typeof RandomRoute
  '/request-game': typeof RequestGameRoute
  '/software': typeof SoftwareRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/games': typeof GamesIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/messages/$peerId': typeof AuthenticatedMessagesPeerIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/posts': typeof AuthenticatedAdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/community': typeof CommunityRouteWithChildren
  '/console-games': typeof ConsoleGamesRoute
  '/random': typeof RandomRoute
  '/request-game': typeof RequestGameRoute
  '/software': typeof SoftwareRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/community/$postId': typeof CommunityPostIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/games/': typeof GamesIndexRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/messages/$peerId': typeof AuthenticatedMessagesPeerIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/_authenticated/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/auth'
    | '/blog'
    | '/community'
    | '/console-games'
    | '/random'
    | '/request-game'
    | '/software'
    | '/admin'
    | '/community/$postId'
    | '/games/$slug'
    | '/profile/$username'
    | '/games/'
    | '/admin/import'
    | '/admin/menu'
    | '/admin/settings'
    | '/messages/$peerId'
    | '/admin/'
    | '/messages/'
    | '/admin/posts/$id'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/auth'
    | '/blog'
    | '/community'
    | '/console-games'
    | '/random'
    | '/request-game'
    | '/software'
    | '/community/$postId'
    | '/games/$slug'
    | '/profile/$username'
    | '/games'
    | '/admin/import'
    | '/admin/menu'
    | '/admin/settings'
    | '/messages/$peerId'
    | '/admin'
    | '/messages'
    | '/admin/posts/$id'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apps'
    | '/auth'
    | '/blog'
    | '/community'
    | '/console-games'
    | '/random'
    | '/request-game'
    | '/software'
    | '/_authenticated/admin'
    | '/community/$postId'
    | '/games/$slug'
    | '/profile/$username'
    | '/games/'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/settings'
    | '/_authenticated/messages/$peerId'
    | '/_authenticated/admin/'
    | '/_authenticated/messages/'
    | '/_authenticated/admin/posts/$id'
    | '/_authenticated/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ConsoleGamesRoute: typeof ConsoleGamesRoute
  RandomRoute: typeof RandomRoute
  RequestGameRoute: typeof RequestGameRoute
  SoftwareRoute: typeof SoftwareRoute
  GamesSlugRoute: typeof GamesSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-game': {
      id: '/request-game'
      path: '/request-game'
      fullPath: '/request-game'
      preLoaderRoute: typeof RequestGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console-games': {
      id: '/console-games'
      path: '/console-games'
      fullPath: '/console-games'
      preLoaderRoute: typeof ConsoleGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/messages/$peerId': {
      id: '/_authenticated/messages/$peerId'
      path: '/messages/$peerId'
      fullPath: '/messages/$peerId'
      preLoaderRoute: typeof AuthenticatedMessagesPeerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/': {
      id: '/_authenticated/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AuthenticatedAdminPostsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
  AuthenticatedAdminPostsIndexRoute: typeof AuthenticatedAdminPostsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
    AuthenticatedAdminPostsIndexRoute: AuthenticatedAdminPostsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMessagesPeerIdRoute: typeof AuthenticatedMessagesPeerIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMessagesPeerIdRoute: AuthenticatedMessagesPeerIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ConsoleGamesRoute: ConsoleGamesRoute,
  RandomRoute: RandomRoute,
  RequestGameRoute: RequestGameRoute,
  SoftwareRoute: SoftwareRoute,
  GamesSlugRoute: GamesSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
